/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":gamelan-sdk-executor-core"))
    api(project(":gamelan-plugin-spi"))
    api(libs.org.slf4j.slf4j.api)
    api(libs.io.quarkus.quarkus.arc)
    api(libs.io.smallrye.reactive.mutiny)
    api(libs.io.quarkus.quarkus.messaging.kafka)
    api(libs.io.quarkus.quarkus.grpc) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "com.google.android", "module" to "annotations"))
    }
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.mockito.mockito.junit.jupiter)
    compileOnly(libs.org.projectlombok.lombok)
}

description = "Gamelan SDK Executor Local"
