/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":gamelan-sdk-executor-core"))
    api(project(":gamelan-plugin-spi"))
    api(libs.org.slf4j.slf4j.api)
    api(libs.io.quarkus.quarkus.arc)
    api(libs.io.smallrye.reactive.mutiny)
    api(libs.io.smallrye.reactive.smallrye.mutiny.vertx.core)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    compileOnly(libs.org.projectlombok.lombok)
}

description = "Gamelan SDK Executor Local"
