/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    compileOnly(project(":gamelan-plugin-spi"))
    compileOnly(libs.org.slf4j.slf4j.api.x1)
}

description = "gamelan-plugin-example"
