/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    id("io.quarkus")
    `java-test-fixtures`
}

dependencies {
    api(project(":gamelan-engine-core"))
    api(project(":gamelan-engine-spi"))
    api(project(":gamelan-protocol-grpc"))
    api(project(":gamelan-protocol-kafka"))
    api(project(":gamelan-executor-registry"))
    api(project(":gamelan-plugin-spi"))
    api(libs.io.quarkus.quarkus.mutiny)
    api(libs.io.quarkus.quarkus.reactive.pg.client)
    api(libs.io.quarkus.quarkus.hibernate.reactive.panache)
    api(libs.io.quarkus.quarkus.jdbc.postgresql)
    api(libs.io.quarkus.quarkus.arc)
    api(libs.io.quarkus.quarkus.hibernate.reactive)
    api(libs.io.quarkus.quarkus.redis.client)
    api(libs.io.quarkus.quarkus.scheduler)
    api(libs.io.quarkus.quarkus.hibernate.validator)
    api(libs.io.quarkus.quarkus.messaging.kafka)
    api(libs.io.quarkus.quarkus.kafka.client)
    api(libs.io.quarkus.quarkus.vertx.http)
    api(libs.io.quarkus.quarkus.grpc) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "com.google.android", "module" to "annotations"))
    }
    api(libs.io.quarkus.quarkus.opentelemetry)
    api(libs.io.netty.netty.transport.native.epoll)
    api(libs.io.smallrye.reactive.smallrye.mutiny.vertx.web.client)
    api(libs.io.smallrye.reactive.smallrye.mutiny.vertx.kafka.client)
    api(libs.io.quarkus.quarkus.smallrye.jwt)
    api(libs.io.quarkus.quarkus.config.yaml)
    api(libs.io.quarkus.quarkus.micrometer)
    api(libs.io.quarkus.quarkus.micrometer.registry.prometheus)
    api(libs.io.quarkus.quarkus.smallrye.fault.tolerance)
    testImplementation(libs.io.quarkus.quarkus.junit)
    testImplementation(libs.io.quarkus.quarkus.junit.mockito)
    testImplementation(libs.io.rest.assured.rest.assured) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.activation", "module" to "activation"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.activation", "module" to "javax.activation-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "jakarta.activation", "module" to "jakarta.activation-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "com.sun.xml.bind", "module" to "jaxb-osgi"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-logging", "module" to "commons-logging"))
    }
    testImplementation(libs.io.quarkus.quarkus.test.security)
    testImplementation(testFixtures(project(":gamelan-engine-spi")))
    testFixturesImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    compileOnly(libs.org.projectlombok.lombok)
}

description = "Gamelan Engine"
