/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":gamelan-engine-spi"))
    api(project(":gamelan-plugin-spi"))
    testImplementation(libs.org.junit.jupiter.junit.jupiter.x2)
}

description = "Gamelan DAG Module"
