/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    `java-test-fixtures`
}

dependencies {
    api(libs.io.smallrye.reactive.mutiny.x1)
    api(libs.org.slf4j.slf4j.api.x1)
    api(libs.io.quarkus.quarkus.arc)
    api(libs.com.fasterxml.jackson.core.jackson.annotations)
    api(libs.com.fasterxml.jackson.core.jackson.databind.x1)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310)
    api(libs.jakarta.validation.jakarta.validation.api)
    api(libs.io.quarkus.quarkus.smallrye.openapi) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "org.jboss.shrinkwrap", "module" to "shrinkwrap-api"))
    }
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.junit.platform.junit.platform.commons)
    testImplementation(libs.org.junit.platform.junit.platform.engine)
    testFixturesImplementation(libs.org.junit.jupiter.junit.jupiter.api)
}

description = "Gamelan Engine API"
