/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":gamelan-sdk-executor-core"))
    api(libs.io.quarkus.quarkus.arc)
    api(libs.io.quarkus.quarkus.rest)
    api(libs.io.quarkus.quarkus.smallrye.jwt)
    api(libs.io.smallrye.reactive.smallrye.mutiny.vertx.web.client)
    testImplementation(libs.io.quarkus.quarkus.junit)
    testImplementation(libs.io.rest.assured.rest.assured) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.activation", "module" to "activation"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.activation", "module" to "javax.activation-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "jakarta.activation", "module" to "jakarta.activation-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "com.sun.xml.bind", "module" to "jaxb-osgi"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-logging", "module" to "commons-logging"))
    }
}

description = "gamelan-test-executor"
