/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":gamelan-engine-spi"))
    api(project(":gamelan-protocol-grpc"))
    api(libs.io.quarkus.quarkus.arc.x1)
    api(libs.org.slf4j.slf4j.api)
    api(libs.io.smallrye.reactive.mutiny.x2)
    api(libs.io.quarkus.quarkus.messaging.kafka.x1)
    compileOnly(libs.org.projectlombok.lombok)
}

description = "Gamelan Kafka Protocol"
