<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>tech.kayys.gamelan</groupId>
        <artifactId>gamelan-parent</artifactId>
        <version>0.1.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>gamelan-core-parent</artifactId>
    <packaging>pom</packaging>

    <properties>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>${quarkus.platform.artifact-id}</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <modules>
        <module>gamelan-engine-spi</module>
        <module>gamelan-plugin-spi</module>
        <module>gamelan-engine-core</module>
        <module>gamelan-sdk-client-core</module>
        <module>gamelan-sdk-executor-core</module>
    </modules>

    <profiles>
        <profile>
            <id>core</id>
        </profile>

        <profile>
            <id>all</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <modules>
                <module>gamelan-executor-registry</module>
                <module>gamelan-engine</module>
                <module>gamelan-runtime-core</module>
                <module>gamelan-executor-runtime-core</module>
                <module>gamelan-executor-runtime</module>
            </modules>
        </profile>

        <profile>
            <id>server</id>
            <modules>
                <module>gamelan-executor-registry</module>
                <module>gamelan-engine</module>
            </modules>
        </profile>

        <profile>
            <id>runtimes</id>
            <modules>
                <module>gamelan-executor-registry</module>
                <module>gamelan-engine</module>
                <module>gamelan-runtime-core</module>
                <module>gamelan-executor-runtime-core</module>
                <module>gamelan-executor-runtime</module>
            </modules>
        </profile>

        <profile>
            <id>executor</id>
            <modules>
                <module>gamelan-executor-registry</module>
                <module>gamelan-executor-runtime-core</module>
                <module>gamelan-executor-runtime</module>
            </modules>
        </profile>
    </profiles>

</project>
