/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":gamelan-sdk-client-core"))
    api(project(":gamelan-protocol-grpc"))
    api(libs.io.smallrye.reactive.mutiny)
    api(libs.io.smallrye.reactive.mutiny.smallrye.context.propagation)
    api(libs.io.smallrye.reactive.smallrye.mutiny.vertx.core) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "com.fasterxml.jackson.core", "module" to "jackson-databind"))
    }
    api(libs.io.smallrye.reactive.smallrye.mutiny.vertx.web.client)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310.x1)
    api(libs.com.fasterxml.jackson.module.jackson.module.parameter.names)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.mockito.mockito.junit.jupiter.x1)
    testImplementation(libs.io.smallrye.reactive.mutiny.test.utils)
    testImplementation(libs.com.github.tomakehurst.wiremock.jre8)
    testImplementation(libs.io.smallrye.config.smallrye.config) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "org.ow2.asm", "module" to "asm"))
    }
    testImplementation(libs.jakarta.enterprise.jakarta.enterprise.cdi.api.x1)
    compileOnly(libs.org.projectlombok.lombok)
    providedCompile(project(":gamelan-engine-spi"))
}

description = "Gamelan SDK Client"
