/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    `java-test-fixtures`
}

dependencies {
    api(libs.io.smallrye.reactive.mutiny.x1)
    api(libs.org.slf4j.slf4j.api.x1)
    api("jakarta.enterprise:jakarta.enterprise.cdi-api:4.1.0")
    api("jakarta.inject:jakarta.inject-api:2.0.1")
    api("org.eclipse.microprofile.config:microprofile-config-api:3.1")
    api("org.eclipse.microprofile.openapi:microprofile-openapi-api:3.1.1")
    api(libs.com.fasterxml.jackson.core.jackson.annotations)
    api(libs.com.fasterxml.jackson.core.jackson.databind.x1)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310)
    api(libs.jakarta.validation.jakarta.validation.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.junit.platform.junit.platform.commons)
    testImplementation(libs.org.junit.platform.junit.platform.engine)
    testFixturesImplementation(libs.org.junit.jupiter.junit.jupiter.api)
}

description = "Gamelan Engine API"
