/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":gamelan-plugin-spi"))
    api(libs.io.smallrye.reactive.mutiny)
    api(libs.org.slf4j.slf4j.api)
}

description = "Gamelan Default Plugins"
