/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
    id("io.quarkus")
}

dependencies {
    api(project(":gamelan-engine-spi"))
    api(libs.io.quarkus.quarkus.grpc) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "com.google.android", "module" to "annotations"))
    }
    api(libs.io.quarkus.quarkus.arc)
    api(libs.org.slf4j.slf4j.api)
    api(libs.com.google.protobuf.protobuf.java.util) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "org.checkerframework", "module" to "checker-qual"))
    }
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    compileOnly(libs.org.projectlombok.lombok)
}

description = "Gamelan gRPC Protocol"
