/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":gamelan-engine-spi"))
    api(libs.io.smallrye.reactive.smallrye.mutiny.vertx.web.client)
    api(libs.com.fasterxml.jackson.core.jackson.annotations.x1)
    api(libs.org.slf4j.slf4j.api)
    compileOnly(libs.org.projectlombok.lombok)
}

description = "Gamelan SDK Client Core"
