/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.io.smallrye.reactive.smallrye.mutiny.vertx.web.client)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    providedCompile(project(":gamelan-plugin-spi"))
}

description = "gamelan-plugin-consul"
