/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":gamelan-sdk-client-core"))
    api(project(":gamelan-engine-spi"))
    compileOnly(libs.org.projectlombok.lombok)
}

description = "Gamelan SDK Client Local"
