/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":gamelan-engine-spi"))
    api(project(":gamelan-plugin-spi"))
    api(libs.io.smallrye.reactive.mutiny)
    api(libs.org.slf4j.slf4j.api)
    api(libs.jakarta.enterprise.jakarta.enterprise.cdi.api.x1)
    api(libs.io.quarkus.quarkus.arc)
    api(libs.io.quarkus.quarkus.rest)
    api(libs.io.quarkus.quarkus.rest.jackson)
    api(libs.io.quarkus.quarkus.scheduler)
    api(project(":gamelan-executor-registry"))
    api(project(":gamelan-engine"))
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(testFixtures(project(":gamelan-engine-spi")))
    testImplementation(testFixtures(project(":gamelan-engine")))
}

description = "Gamelan Runtime Core"
