/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":gamelan-plugin-spi"))
    api(libs.io.quarkus.quarkus.arc)
    api(libs.org.slf4j.slf4j.api)
    api(libs.io.smallrye.reactive.mutiny)
    api(libs.io.quarkus.quarkus.scheduler)
    api(libs.io.quarkus.quarkus.micrometer)
    api(libs.io.quarkus.quarkus.micrometer.registry.prometheus)
    api(libs.io.quarkus.quarkus.redis.client)
    api(libs.io.quarkus.quarkus.vertx)
    api(libs.io.quarkus.quarkus.hibernate.validator)
    api(libs.io.quarkus.quarkus.hibernate.reactive.panache)
    api(libs.io.quarkus.quarkus.reactive.pg.client)
    api(libs.io.quarkus.quarkus.cache)
    testImplementation(libs.io.quarkus.quarkus.junit)
    testImplementation(libs.io.quarkus.quarkus.junit.mockito)
    testImplementation(libs.io.quarkus.quarkus.test.h2)
}

description = "Gamelan Executor Registry"
