/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":gamelan-engine-spi"))
    api(project(":gamelan-plugin-spi"))
    api(libs.io.smallrye.reactive.mutiny)
    api(libs.org.slf4j.slf4j.api.x1)
    api(libs.io.quarkus.quarkus.arc)
    api(libs.io.quarkus.quarkus.reactive.pg.client)
    testImplementation(libs.io.quarkus.quarkus.junit)
    testImplementation(libs.io.quarkus.quarkus.junit.mockito)
}

description = "Gamelan Engine Core"
